import Head from 'next/head'

import Image from 'next/image'
//import { Inter } from 'next/font/google'
import { useRouter } from 'next/router'
import { useContext } from 'react'
import { AuthContext } from '../context/auth'
import Feed from '../component/Feed'
//const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
    <Head>
      <title>Reels</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
   <Feed/>
  </div>
)
  
}
